image: docker:stable

services:
  - docker:dind

variables:
  DOCKER_IMAGE_FULL_NAME: $CI_REGISTRY_IMAGE:latest

before_script:
  - apk update && apk add bash
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - cd ${CI_PROJECT_DIR}/docker
    - docker build -t $DOCKER_IMAGE_FULL_NAME .
    - docker push $DOCKER_IMAGE_FULL_NAME
  only:
    - master

test:
  stage: test
  script:
    - docker pull $DOCKER_IMAGE_FULL_NAME
    - cp ${CI_PROJECT_DIR}/mkdockerize.sh ${CI_PROJECT_DIR}/examples/engineering-docs
    - cd ${CI_PROJECT_DIR}/examples/engineering-docs
    - DOCKER_NAME=$DOCKER_IMAGE_FULL_NAME bash mkdockerize.sh
  only:
    - master

